name: audio-isolation
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10.10
  - pip=23.1
  - matplotlib=3.7.1
  - mir_eval=0.6
  - ffmpeg<4.4
  - ipython=8.12.0
  - pip:
    - torchaudio==2.0.0
    - torchvision==0.15.0