batch_size: 10
loss_type: L1
model_params:
  activation: sigmoid
  bidirectional: true
  dropout: 0.3
  hidden_size: 64
  hop_length: 32
  num_audio_channels: 1
  num_features: 128
  num_filters: 128
  num_layers: 3
  num_sources: 2
  window_type: sqrt_hann
model_type: Filterbank
optimizer_params:
  lr: 0.001
save_name: filterbank_default_L1
stft_params: null
test_folder: data/musdb18hq/test
train_folder: data/musdb18hq/train
train_generator_params:
  coherent_prob: 1.0
  num_mixtures: 1000000
train_params:
  epoch_length: 10
  max_epochs: 50
valid_folder: data/musdb18hq/validation
valid_generator_params:
  coherent_prob: 1.0
  num_mixtures: 10
