batch_size: 10
loss_type: L2
model_params:
  activation: sigmoid
  bidirectional: true
  dropout: 0.3
  hidden_size: 64
  hop_length: 128
  num_audio_channels: 1
  num_features: 512
  num_filters: 512
  num_layers: 2
  num_sources: 1
  window_type: sqrt_hann
model_type: Filterbank
optimizer_params:
  lr: 0.005
save_name: filterbank_1source
stft_params: null
test_folder: data/musdb18hq/test
train_folder: data/musdb18hq/train
train_generator_params:
  coherent_prob: 0.85
  num_mixtures: 1000000
train_params:
  epoch_length: 25
  max_epochs: 25
valid_folder: data/musdb18hq/validation
valid_generator_params:
  coherent_prob: 1.0
  num_mixtures: 10
