batch_size: 10
loss_type: L1
model_params:
  activation: sigmoid
  bidirectional: true
  dropout: 0.1
  hidden_size: 128
  num_audio_channels: 1
  num_layers: 3
  num_sources: 1
model_type: Mask
optimizer_params:
  lr: 0.001
save_name: ST_mask_3layer
stft_params:
  hop_length: 128
  window_length: 512
  window_type: sqrt_hann
test_folder: data/musdb18hq/test
train_folder: data/musdb18hq/train
train_generator_params:
  coherent_prob: 1.0
  num_mixtures: 1000000
train_params:
  epoch_length: 25
  max_epochs: 25
valid_folder: data/musdb18hq/validation
valid_generator_params:
  coherent_prob: 1.0
  num_mixtures: 10
