model_type: Mask
loss_type: L1
stft_params: 
  window_length: 128
  hop_length: 32
  window_type: 'sqrt_hann'
train_folder: 'data/musdb18hq/train'
valid_folder: 'data/musdb18hq/validation'
test_folder: 'data/musdb18hq/test'
train_generator_params:
  num_mixtures: 1000000
  coherent_prob: 1.0
valid_generator_params:
  num_mixtures: 10
  coherent_prob: 1.0
batch_size: 10
model_params:
  num_audio_channels: 1
  hidden_size: 64
  num_layers: 2
  bidirectional: True
  dropout: 0
  num_sources: 4
  activation: ['sigmoid','unit_norm']
optimizer_params:
  lr: 0.001
train_params:
  epoch_length: 10
  max_epochs: 10
save_name: 'mask_default'