model_type: Filterbank
loss_type: L2
stft_params: null
train_folder: 'data/musdb18hq/train'
valid_folder: 'data/musdb18hq/validation'
test_folder: 'data/musdb18hq/test'
train_generator_params:
  num_mixtures: 1000000
  coherent_prob: 1.0
valid_generator_params:
  num_mixtures: 10
  coherent_prob: 1.0
batch_size: 10
model_params:
  num_features: 64
  num_audio_channels: 1
  hidden_size: 50
  num_layers: 3
  bidirectional: True
  dropout: 0.5
  num_sources: 1
  activation: 'sigmoid'
  window_type: 'sqrt_hann'
  num_filters: 64
  hop_length: 32
optimizer_params:
  lr: 0.005
train_params:
  epoch_length: 25
  max_epochs: 15
save_name: 'filterbank_3L_0.5P_64f'